### ISSUE TITLE
建议：子文件夹折叠功能

### ISSUE THREAD

**Issue by GuangChen2333** [Enaium/JavaOctetEditor#14]
### 建议添加单个子文件夹折叠功能
如一个包 `a.b.c.d.e.f.g`
其中每个包都仅有一个子包
应直接在gui中呈现为 `a.b.c.d.e.f.g`
而无需用户逐个点开

如图：
![example](https://s1.328888.xyz/2022/08/24/wjWJX.png)

**Comment by Enaium** [comment]
可以右键，展开全部

**Comment by Enaium** [comment]
completed
